cmake_minimum_required(VERSION 3.21)

set(input_args --rows 19 --cols 23 --b-cols 13 --nnz-per-row 3 --b-nnz-per-row 2)
if(INPUT_CASE STREQUAL "hierarchical")
    set(ranks 8)
    list(APPEND input_args --logical-node-size 2)
elseif(INPUT_CASE STREQUAL "invalid_grid")
    set(ranks 2)
    list(APPEND input_args --logical-node-size 1)
    set(expected_error "requires a square number of nodes")
elseif(INPUT_CASE STREQUAL "invalid_logical")
    set(ranks 4)
    list(APPEND input_args --logical-node-size 3)
    set(expected_error "requires a positive divisor of ranks")
else()
    message(FATAL_ERROR "Unknown case ${INPUT_CASE}")
endif()
file(REMOVE "${RESULTS_FILE}")
execute_process(
    COMMAND "${MPIEXEC_EXECUTABLE}" "${MPIEXEC_NUMPROC_FLAG}" ${ranks}
            ${MPIEXEC_PREFLAGS} "${BENCHMARK}" ${MPIEXEC_POSTFLAGS}
            ${input_args} --warmup 1 --repeats 2 --trials 2 --threads 2 --results "${RESULTS_FILE}"
    RESULT_VARIABLE exit_code OUTPUT_VARIABLE output ERROR_VARIABLE error_output TIMEOUT 45
)
if(DEFINED expected_error)
    if(NOT "${exit_code}" MATCHES "^[1-9][0-9]*$")
        message(FATAL_ERROR "Expected nonzero exit, got ${exit_code}\n${output}\n${error_output}")
    endif()
    string(FIND "${output}\n${error_output}" "${expected_error}" position)
    if(position EQUAL -1 OR EXISTS "${RESULTS_FILE}")
        message(FATAL_ERROR "Unexpected topology failure\n${output}\n${error_output}")
    endif()
    return()
endif()
if(NOT "${exit_code}" STREQUAL "0")
    message(FATAL_ERROR "Trident failed: ${exit_code}\n${output}\n${error_output}")
endif()
file(STRINGS "${RESULTS_FILE}" lines)
list(GET lines 0 header)
list(GET lines -1 row)
string(REPLACE "\t" ";" fields "${header}")
string(REPLACE "\t" ";" values "${row}")
list(LENGTH fields field_count)
list(LENGTH values value_count)
if(NOT field_count EQUAL value_count)
    message(FATAL_ERROR "TSV field count mismatch")
endif()
set(expected_nodes 4)
set(expected_ranks_per_node 2)
set(expected_grid_rows 2)
set(expected_grid_cols 2)
set(expected_topology logical_test)
set(expected_validation PASS)
if(NOT DEFINED EXPECTED_PROTOCOL)
    set(EXPECTED_PROTOCOL trident_staged_csr_v1)
endif()
if(NOT DEFINED EXPECTED_INTER_TRANSPORT)
    set(EXPECTED_INTER_TRANSPORT two_sided_static_cannon)
endif()
set(expected_benchmark_protocol "${EXPECTED_PROTOCOL}")
set(expected_inter_node_transport "${EXPECTED_INTER_TRANSPORT}")
set(expected_intra_node_transport trident_two_sided)
foreach(field IN ITEMS nodes ranks_per_node grid_rows grid_cols topology validation benchmark_protocol
                       inter_node_transport intra_node_transport)
    list(FIND fields "${field}" index)
    if(index LESS 0)
        message(FATAL_ERROR "Missing ${field}")
    endif()
    list(GET values ${index} actual)
    if(NOT "${actual}" STREQUAL "${expected_${field}}")
        message(FATAL_ERROR "${field}: expected ${expected_${field}}, got ${actual}")
    endif()
endforeach()
foreach(field IN ITEMS distribution_seconds plan_setup_seconds first_product_seconds
                       inter_node_p90_seconds intra_node_p90_seconds communication_p90_seconds
                       compute_p90_seconds end_to_end_p90_seconds gather_seconds)
    list(FIND fields "${field}" index)
    if(index LESS 0)
        message(FATAL_ERROR "Missing timing ${field}")
    endif()
    list(GET values ${index} actual)
    if(NOT actual MATCHES "^[0-9]+([.][0-9]+)?([eE][-+]?[0-9]+)?$")
        message(FATAL_ERROR "Invalid timing ${field}=${actual}")
    endif()
endforeach()
